-- backend/db/schema.sql

-- Enable UUID extension if needed
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- User Roles ENUM
CREATE TYPE user_role AS ENUM ('ADMIN', 'PROFESSOR', 'STUDENT');

-- Users Table
CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL, -- Assuming hashed passwords
    role user_role NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Global Settings Table (Admin managed)
CREATE TABLE settings (
    key VARCHAR(50) PRIMARY KEY,
    value VARCHAR(255) NOT NULL,
    description TEXT
);

-- Insert default radius setting
INSERT INTO settings (key, value, description) 
VALUES ('attendance_radius_meters', '20', 'Maximum distance allowed for student check-in');

-- Timetable Table (Master schedule)
CREATE TABLE timetable (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    professor_id UUID REFERENCES users(id) ON DELETE CASCADE,
    subject_name VARCHAR(255) NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    days_of_week VARCHAR(50) NOT NULL, -- e.g., 'Monday,Wednesday,Friday'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Attendance Sessions Table (Anchor generated by Professor)
CREATE TABLE attendance_sessions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    timetable_id UUID REFERENCES timetable(id) ON DELETE CASCADE,
    professor_id UUID REFERENCES users(id) ON DELETE CASCADE,
    otp VARCHAR(6) NOT NULL,
    anchor_latitude DECIMAL(10, 8) NOT NULL,
    anchor_longitude DECIMAL(11, 8) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Attendance Records Table (Student Check-ins)
CREATE TABLE attendance_records (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    session_id UUID REFERENCES attendance_sessions(id) ON DELETE CASCADE,
    student_id UUID REFERENCES users(id) ON DELETE CASCADE,
    distance_meters DECIMAL(10, 2) NOT NULL,
    status VARCHAR(50) DEFAULT 'PRESENT',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(session_id, student_id) -- Prevent duplicate check-ins
);

-- Indexes for performance
CREATE INDEX idx_sessions_otp ON attendance_sessions(otp);
CREATE INDEX idx_sessions_expires_at ON attendance_sessions(expires_at);
CREATE INDEX idx_records_student ON attendance_records(student_id);
